version: "3"

services:
  collabora:
    image: collabora/code
    restart: unless-stopped
    environment:
      - domain=${NC_DOMAIN}
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:net.post_allow.host[0]=::ffff:10\.[0-9\.]+ --o:storage.wopi.host[0]=::ffff:10\.[0-9\.]+ --o:storage.wopi.host[1]=${NC_DOMAIN}
      - SLEEPFORDEBUGGER=0
    networks:
      - public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.passHostHeader=true"
        - "traefik.docker.network=public"
        - "traefik.http.services.{{ env \"OFFICE_URL\" }}.loadbalancer.server.port=9980"
        - "traefik.http.routers.{{ env \"OFFICE_URL\" }}.entrypoints=websecure"
        - "traefik.http.routers.{{ env \"OFFICE_URL\" }}.rule=Host(`${OFFICE_URL}`)"
        - "traefik.http.middlewares.{{ env \"OFFICE_URL\" }}.compress=true"
        - "traefik.http.routers.{{ env \"OFFICE_URL\" }}.tls.certresolver=myresolver"
        - "traefik.http.routers.{{ env \"OFFICE_URL\" }}.tls=true"
      replicas: 1
      resources:
        limits:
          cpus: '4'
          memory: '1024M'
      placement:
        constraints:
          - "node.role==worker"

networks:
  public:
    external: true

volumes:
  collab_proxy_conf:
